"use client";

import React, { useState, useEffect } from "react";
import { useAuth } from "@/lib/auth-context";
import { db, mockDb, ClubMember, PointTransaction, Referral, Coupon, ClubConfig, ClubReward, ClientPhoto, FraudAlert, Review } from "@/lib/db";
import {
  Sparkles, Users, Award, ShieldAlert, Settings, BarChart2, Search,
  Plus, Trash2, Edit2, CheckCircle, Ban, AlertTriangle, RefreshCw,
  X, Download, Star, Camera, Gift, Check, Clock, ChevronRight
} from "lucide-react";

export default function AdminClubPachecaPage() {
  const { user } = useAuth();
  const [activeTab, setActiveTab] = useState<"resumen" | "miembros" | "moderacion" | "premios" | "config" | "analiticas">("resumen");
  
  // Data States loaded from mockDb
  const [members, setMembers] = useState<ClubMember[]>([]);
  const [config, setConfig] = useState<ClubConfig | null>(null);
  const [rewards, setRewards] = useState<ClubReward[]>([]);
  const [reviews, setReviews] = useState<Review[]>([]);
  const [photos, setPhotos] = useState<ClientPhoto[]>([]);
  const [alerts, setAlerts] = useState<FraudAlert[]>([]);
  const [transactions, setTransactions] = useState<PointTransaction[]>([]);
  const [referrals, setReferrals] = useState<Referral[]>([]);

  // Search and filter states
  const [memberSearch, setMemberSearch] = useState("");
  
  // Selected entities for modals
  const [selectedMember, setSelectedMember] = useState<ClubMember | null>(null);
  const [showAdjustPointsModal, setShowAdjustPointsModal] = useState(false);
  const [adjustAmount, setAdjustAmount] = useState(0);
  const [adjustReason, setAdjustReason] = useState("");
  
  // Rewards CRUD states
  const [editingReward, setEditingReward] = useState<ClubReward | null>(null);
  const [showRewardModal, setShowRewardModal] = useState(false);
  const [rewardForm, setRewardForm] = useState<Omit<ClubReward, "id">>({
    name: "",
    description: "",
    points_required: 500,
    benefit_type: "percentage",
    benefit_value: 5,
    min_purchase_amount: 0,
    expires_days: 30,
    stock: 100,
    is_active: true,
    image_url: ""
  });

  // Moderation filter
  const [modSubTab, setModSubTab] = useState<"reseñas" | "fotos" | "fraude">("reseñas");

  // Load data
  const loadData = () => {
    setMembers([...mockDb.club_members]);
    setConfig({ ...mockDb.club_config });
    setRewards([...mockDb.club_rewards]);
    setReviews([...mockDb.reviews]);
    setPhotos([...mockDb.client_photos]);
    setAlerts([...mockDb.fraud_alerts]);
    setTransactions([...mockDb.point_transactions]);
    setReferrals([...mockDb.referrals]);
  };

  useEffect(() => {
    loadData();
  }, []);

  // Recalculate states after database writes
  const handleRefresh = () => {
    loadData();
  };

  // KPIs calculations
  const totalMembers = members.length;
  const newMembersThisMonth = members.filter(m => {
    const regDate = new Date(m.registered_at);
    const now = new Date();
    return regDate.getMonth() === now.getMonth() && regDate.getFullYear() === now.getFullYear();
  }).length;

  const pointsEmitted = transactions.filter(t => t.amount > 0 && t.status === "acreditado").reduce((acc, t) => acc + t.amount, 0);
  const pointsRedeemed = Math.abs(transactions.filter(t => t.amount < 0).reduce((acc, t) => acc + t.amount, 0));
  const pointsPending = members.reduce((acc, m) => acc + (m.points_pending || 0), 0);

  const totalReferrals = referrals.length;
  const convertedReferrals = referrals.filter(r => r.status === "compra_confirmada" || r.status === "beneficio_acreditado").length;
  const referralConversionRate = totalReferrals > 0 ? ((convertedReferrals / totalReferrals) * 100).toFixed(1) : "0.0";
  
  // Calculate total purchases generated by referrers (orders using a referral coupon)
  const referralCouponsUsed = mockDb.coupons.filter(c => c.is_used && c.code.startsWith("REF-") && c.used_order_id);
  const referralOrdersRevenue = referralCouponsUsed.reduce((acc, c) => {
    const order = mockDb.orders.find(o => o.id === c.used_order_id);
    return acc + (order ? order.total_amount : 0);
  }, 0);

  const totalCouponsGenerated = mockDb.coupons.length;
  const totalCouponsUsed = mockDb.coupons.filter(c => c.is_used).length;

  const pendingReviewsCount = reviews.filter(r => r.status === "pending").length;
  const pendingPhotosCount = photos.filter(p => p.status === "pending").length;
  const pendingAlertsCount = alerts.filter(a => a.status === "requiere_revision").length;

  // Member Search
  const filteredMembers = members.filter(m => {
    const profile = mockDb.profiles.find(p => p.id === m.profile_id);
    const cust = mockDb.customers.find(c => c.profile_id === m.profile_id);
    const searchString = `${profile?.first_name} ${profile?.last_name} ${profile?.email} ${cust?.phone} ${m.referral_code}`.toLowerCase();
    return searchString.includes(memberSearch.toLowerCase());
  });

  // Manual Adjust Points
  const handleAdjustPointsSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedMember || adjustAmount === 0 || !adjustReason.trim()) return;

    try {
      const adminId = user?.email || "admin@pacheca.com";
      await db.club.members.addPointsManual(selectedMember.id, adjustAmount, adminId, adjustReason);
      alert(`Puntos ajustados con éxito (${adjustAmount > 0 ? "+" : ""}${adjustAmount})`);
      setShowAdjustPointsModal(false);
      setAdjustAmount(0);
      setAdjustReason("");
      
      // Refresh selected member info
      const updated = mockDb.club_members.find(m => m.id === selectedMember.id) || null;
      setSelectedMember(updated);
      loadData();
    } catch (err: any) {
      alert(`Error al ajustar puntos: ${err.message || err}`);
    }
  };

  // Block/Unblock Member
  const handleToggleBlockMember = (memberId: string) => {
    const mem = mockDb.club_members.find(m => m.id === memberId);
    if (!mem) return;
    mem.is_blocked = !mem.is_blocked;
    alert(`Miembro ${mem.is_blocked ? "bloqueado" : "desbloqueado"} con éxito.`);
    loadData();
    if (selectedMember?.id === memberId) {
      setSelectedMember({ ...mem });
    }
  };

  // Change Level
  const handleChangeLevel = (memberId: string, level: "Pacheca" | "Pacheca Plus" | "Pacheca VIP") => {
    const mem = mockDb.club_members.find(m => m.id === memberId);
    if (!mem) return;
    mem.level = level;
    alert(`Nivel modificado a: ${level}`);
    loadData();
    if (selectedMember?.id === memberId) {
      setSelectedMember({ ...mem });
    }
  };

  // Update Config
  const handleConfigUpdate = async (updates: Partial<ClubConfig>) => {
    try {
      await db.club.config.update(updates);
      alert("Configuración actualizada con éxito.");
      loadData();
    } catch (err: any) {
      alert(`Error al actualizar configuración: ${err.message || err}`);
    }
  };

  // Create or Update Reward
  const handleRewardSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      if (editingReward) {
        await db.club.rewards.update(editingReward.id, rewardForm);
        alert("Premio actualizado con éxito.");
      } else {
        await db.club.rewards.create(rewardForm);
        alert("Premio creado con éxito.");
      }
      setShowRewardModal(false);
      setEditingReward(null);
      loadData();
    } catch (err: any) {
      alert(`Error al guardar premio: ${err.message || err}`);
    }
  };

  const handleOpenNewRewardModal = () => {
    setEditingReward(null);
    setRewardForm({
      name: "",
      description: "",
      points_required: 500,
      benefit_type: "percentage",
      benefit_value: 5,
      min_purchase_amount: 0,
      expires_days: 45,
      stock: 50,
      is_active: true,
      image_url: ""
    });
    setShowRewardModal(true);
  };

  const handleOpenEditRewardModal = (reward: ClubReward) => {
    setEditingReward(reward);
    setRewardForm({
      name: reward.name,
      description: reward.description,
      points_required: reward.points_required,
      benefit_type: reward.benefit_type,
      benefit_value: reward.benefit_value,
      min_purchase_amount: reward.min_purchase_amount,
      expires_days: reward.expires_days,
      stock: reward.stock,
      is_active: reward.is_active,
      image_url: reward.image_url || ""
    });
    setShowRewardModal(true);
  };

  const handleDeleteReward = async (id: string) => {
    if (!confirm("¿Estás segura de eliminar esta recompensa del catálogo?")) return;
    const ok = await db.club.rewards.delete(id);
    if (ok) {
      alert("Recompensa eliminada.");
      loadData();
    }
  };

  // Moderation Actions
  const handleApproveReview = async (reviewId: string) => {
    const adminId = user?.email || "admin@pacheca.com";
    const result = await db.club.reviews.approve(reviewId, adminId);
    if (result) {
      alert("Reseña aprobada. Puntos acreditados si correspondía.");
      loadData();
    }
  };

  const handleRejectReview = async (reviewId: string) => {
    const result = await db.club.reviews.reject(reviewId);
    if (result) {
      alert("Reseña rechazada.");
      loadData();
    }
  };

  const handleApprovePhoto = async (photoId: string) => {
    const adminId = user?.email || "admin@pacheca.com";
    const result = await db.club.photos.approve(photoId, adminId);
    if (result) {
      alert("Foto aprobada. Puntos acreditados con éxito.");
      loadData();
    }
  };

  const handleRejectPhoto = async (photoId: string) => {
    const result = await db.club.photos.reject(photoId);
    if (result) {
      alert("Foto rechazada.");
      loadData();
    }
  };

  const handleResolveAlert = (alertId: string, resolution: "aprobado" | "bloqueado") => {
    const fraudAlert = mockDb.fraud_alerts.find(a => a.id === alertId);
    if (!fraudAlert) return;
    fraudAlert.status = resolution;
    
    // If blocked, block the member as well
    if (resolution === "bloqueado" && fraudAlert.member_id) {
      const mem = mockDb.club_members.find(m => m.id === fraudAlert.member_id);
      if (mem) mem.is_blocked = true;
    }
    
    fraudAlert.description += ` [Resuelto: ${resolution} por ${user?.email || "admin"}]`;
    fraudAlert.created_at = new Date().toISOString();
    fraudAlert.status = resolution;
    
    loadData();
    alert(`Alerta marcada como ${resolution.toUpperCase()}.`);
  };

  // CSV Exporter
  const handleExportMembers = () => {
    const headers = ["ID", "Nombre", "Email", "Puntos Disponibles", "Puntos Pendientes", "Nivel", "Codigo Referido", "Fecha Registro", "Estado"];
    const rows = members.map(m => {
      const profile = mockDb.profiles.find(p => p.id === m.profile_id);
      return [
        m.id,
        profile ? `${profile.first_name} ${profile.last_name}` : "N/A",
        profile?.email || "N/A",
        m.points_balance,
        m.points_pending,
        m.level,
        m.referral_code,
        new Date(m.registered_at).toLocaleDateString(),
        m.is_blocked ? "Bloqueado" : "Activo"
      ];
    });
    const csvString = [headers.join(";"), ...rows.map(e => e.map(val => `"${String(val).replace(/"/g, '""')}"`).join(";"))].join("\n");
    const blob = new Blob(["\uFEFF" + csvString], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute("download", `club_pacheca_miembros_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // ROI / Metrics values
  const recurringMembersCount = members.filter(m => {
    const ordersCount = mockDb.orders.filter(o => o.customer_id === mockDb.customers.find(c => c.profile_id === m.profile_id)?.id).length;
    return ordersCount > 1;
  }).length;

  const totalVoucherDiscountCosts = mockDb.coupons
    .filter(c => c.is_used)
    .reduce((acc, c) => acc + (c.discount_type === "percentage" ? (c.discount_value * 5000 / 100) : c.discount_value), 0); // Estimated 5000 ticket

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex justify-between items-center border-b border-border-brand pb-4">
        <div>
          <h1 className="text-xl font-bold font-display text-text-dark uppercase tracking-wider flex items-center">
            <Sparkles className="h-5 w-5 mr-2 text-accent" />
            Club Pacheca & Fidelización
          </h1>
          <p className="text-xs text-text-muted mt-1">
            Panel administrativo para gestionar miembros, moderar opiniones, administrar recompensas y configurar reglas.
          </p>
        </div>
        <button
          onClick={handleRefresh}
          className="p-2 border border-border-brand rounded-lg hover:bg-bg-light text-text-muted hover:text-text-dark transition-colors flex items-center gap-1.5 text-xs font-semibold"
        >
          <RefreshCw className="h-4 w-4" />
          Actualizar
        </button>
      </div>

      {/* Tabs */}
      <div className="flex border-b border-border-brand overflow-x-auto gap-2">
        {(["resumen", "miembros", "moderacion", "premios", "config", "analiticas"] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`py-3 px-4 text-xs font-bold uppercase tracking-wider whitespace-nowrap border-b-2 transition-all ${
              activeTab === tab
                ? "border-black text-text-dark font-extrabold"
                : "border-transparent text-text-muted hover:text-text-dark"
            }`}
          >
            {tab === "resumen" && "Resumen"}
            {tab === "miembros" && `Miembros (${members.length})`}
            {tab === "moderacion" && `Moderación (${pendingReviewsCount + pendingPhotosCount + pendingAlertsCount})`}
            {tab === "premios" && "Premios & Catálogo"}
            {tab === "config" && "Reglas del Club"}
            {tab === "analiticas" && "Analíticas & ROI"}
          </button>
        ))}
      </div>

      {/* TAB CONTENT: RESUMEN */}
      {activeTab === "resumen" && (
        <div className="space-y-6">
          {/* Metrics Grid */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-1">
              <p className="text-[10px] uppercase font-bold text-text-muted tracking-wider">Miembros Activos</p>
              <div className="flex items-baseline space-x-2">
                <span className="text-xl font-bold font-display text-text-dark">{totalMembers}</span>
                <span className="text-[10px] text-success font-semibold">+{newMembersThisMonth} este mes</span>
              </div>
            </div>
            
            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-1">
              <p className="text-[10px] uppercase font-bold text-text-muted tracking-wider">Puntos Acreditados</p>
              <p className="text-xl font-bold font-display text-text-dark">
                {new Intl.NumberFormat("es-AR").format(pointsEmitted)}
              </p>
            </div>

            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-1">
              <p className="text-[10px] uppercase font-bold text-text-muted tracking-wider">Puntos Canjeados</p>
              <div className="flex items-baseline space-x-2">
                <span className="text-xl font-bold font-display text-text-dark">
                  {new Intl.NumberFormat("es-AR").format(pointsRedeemed)}
                </span>
                <span className="text-[10px] text-text-muted font-medium">
                  ({totalMembers > 0 ? ((pointsRedeemed / pointsEmitted) * 100).toFixed(0) : 0}% canjeados)
                </span>
              </div>
            </div>

            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-1">
              <p className="text-[10px] uppercase font-bold text-text-muted tracking-wider">Conversión Referidos</p>
              <div className="flex items-baseline space-x-2">
                <span className="text-xl font-bold font-display text-text-dark">{referralConversionRate}%</span>
                <span className="text-[10px] text-text-muted font-medium">
                  {convertedReferrals} de {totalReferrals}
                </span>
              </div>
            </div>
          </div>

          {/* Quick Actions / Pendientes */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* Pendientes Card */}
            <div className="bg-white border border-border-brand rounded-xl p-5 shadow-2xs space-y-4">
              <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center">
                <AlertTriangle className="h-4 w-4 mr-2 text-warning" />
                Pendientes de Moderación
              </h3>
              <div className="divide-y divide-border-brand text-xs">
                <div className="py-2.5 flex justify-between items-center">
                  <span>Opiniones de producto</span>
                  <span className={`px-2 py-0.5 rounded-full font-bold ${pendingReviewsCount > 0 ? "bg-amber-100 text-amber-800" : "bg-bg-light text-text-muted"}`}>
                    {pendingReviewsCount}
                  </span>
                </div>
                <div className="py-2.5 flex justify-between items-center">
                  <span>Fotos de clientas</span>
                  <span className={`px-2 py-0.5 rounded-full font-bold ${pendingPhotosCount > 0 ? "bg-amber-100 text-amber-800" : "bg-bg-light text-text-muted"}`}>
                    {pendingPhotosCount}
                  </span>
                </div>
                <div className="py-2.5 flex justify-between items-center">
                  <span>Alertas de antifraude</span>
                  <span className={`px-2 py-0.5 rounded-full font-bold ${pendingAlertsCount > 0 ? "bg-red-100 text-red-800" : "bg-bg-light text-text-muted"}`}>
                    {pendingAlertsCount}
                  </span>
                </div>
              </div>
              <button
                onClick={() => { setActiveTab("moderacion"); setModSubTab("reseñas"); }}
                className="w-full text-center py-2 bg-black text-white hover:bg-neutral-800 transition-colors rounded-lg font-bold text-xs uppercase tracking-wider shadow-2xs"
              >
                Ir a Moderación
              </button>
            </div>

            {/* Config Resumen Card */}
            <div className="bg-white border border-border-brand rounded-xl p-5 shadow-2xs space-y-4">
              <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center">
                <Settings className="h-4 w-4 mr-2 text-accent" />
                Parámetros Clave
              </h3>
              <div className="space-y-3 text-xs">
                <div className="flex justify-between">
                  <span className="text-text-muted">Bienvenida:</span>
                  <span className="font-bold text-text-dark">{config?.points_welcome} pts</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-muted">Conversión Compra:</span>
                  <span className="font-bold text-text-dark">1 pt cada ${config?.money_to_points_ratio}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-muted">Premio Referido:</span>
                  <span className="font-bold text-text-dark">{config?.points_per_referral} pts</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-muted">Descuento Referida:</span>
                  <span className="font-bold text-text-dark">{config?.referral_discount_friend}% OFF</span>
                </div>
              </div>
              <button
                onClick={() => setActiveTab("config")}
                className="w-full text-center py-2 border border-border-brand text-text-dark hover:bg-bg-light transition-colors rounded-lg font-bold text-xs uppercase tracking-wider"
              >
                Configurar Reglas
              </button>
            </div>

            {/* Referidos ROI Card */}
            <div className="bg-white border border-border-brand rounded-xl p-5 shadow-2xs space-y-4">
              <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center">
                <BarChart2 className="h-4 w-4 mr-2 text-success" />
                Impacto de Referidos
              </h3>
              <div className="space-y-3 text-xs">
                <div className="flex justify-between">
                  <span className="text-text-muted">Ventas Generadas:</span>
                  <span className="font-bold text-success">
                    {new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" }).format(referralOrdersRevenue)}
                  </span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-muted">Cupones Emitidos:</span>
                  <span className="font-bold text-text-dark">{totalCouponsGenerated}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-muted">Cupones Usados:</span>
                  <span className="font-bold text-text-dark">{totalCouponsUsed}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-text-muted">Tasa de Uso:</span>
                  <span className="font-bold text-text-dark">
                    {totalCouponsGenerated > 0 ? ((totalCouponsUsed / totalCouponsGenerated) * 100).toFixed(0) : 0}%
                  </span>
                </div>
              </div>
              <button
                onClick={() => setActiveTab("analiticas")}
                className="w-full text-center py-2 border border-border-brand text-text-dark hover:bg-bg-light transition-colors rounded-lg font-bold text-xs uppercase tracking-wider"
              >
                Ver Analíticas
              </button>
            </div>

          </div>
        </div>
      )}

      {/* TAB CONTENT: MIEMBROS */}
      {activeTab === "miembros" && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row gap-3 justify-between items-stretch sm:items-center">
            
            {/* Search */}
            <div className="relative flex-1 max-w-md">
              <Search className="absolute left-3 top-2.5 h-4 w-4 text-text-muted" />
              <input
                type="text"
                placeholder="Buscar por nombre, email, referido..."
                value={memberSearch}
                onChange={(e) => setMemberSearch(e.target.value)}
                className="pl-9 pr-4 py-2 w-full text-xs border border-border-brand rounded-lg focus:outline-none focus:border-accent"
              />
            </div>

            {/* Actions */}
            <button
              onClick={handleExportMembers}
              className="flex items-center justify-center gap-1.5 px-4 py-2 border border-border-brand hover:bg-bg-light text-text-dark font-bold text-xs uppercase tracking-wider rounded-lg transition-colors"
            >
              <Download className="h-4 w-4" />
              Exportar CSV
            </button>
          </div>

          {/* Members Table */}
          <div className="bg-white border border-border-brand rounded-xl overflow-hidden shadow-2xs">
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className="bg-bg-light border-b border-border-brand uppercase tracking-wider font-bold text-text-muted text-[10px]">
                    <th className="p-4">Miembro / Email</th>
                    <th className="p-4">Código Ref.</th>
                    <th className="p-4">Nivel</th>
                    <th className="p-4 text-right">Puntos Disponibles</th>
                    <th className="p-4 text-right">Pendientes</th>
                    <th className="p-4 text-center">Estado</th>
                    <th className="p-4 text-right">Acción</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border-brand">
                  {filteredMembers.length === 0 ? (
                    <tr>
                      <td colSpan={7} className="p-8 text-center text-text-muted">
                        No se encontraron miembros del club con el filtro actual.
                      </td>
                    </tr>
                  ) : (
                    filteredMembers.map(m => {
                      const profile = mockDb.profiles.find(p => p.id === m.profile_id);
                      return (
                        <tr key={m.id} className="hover:bg-bg-light/40 transition-colors">
                          <td className="p-4">
                            <div className="font-bold text-text-dark">
                              {profile ? `${profile.first_name} ${profile.last_name}` : "N/A"}
                            </div>
                            <div className="text-[10px] text-text-muted mt-0.5">{profile?.email || "Sin email"}</div>
                          </td>
                          <td className="p-4 font-mono font-bold text-text-dark">{m.referral_code}</td>
                          <td className="p-4">
                            <span className={`px-2 py-0.5 rounded-full font-bold text-[9px] border ${
                              m.level === "Pacheca VIP"
                                ? "bg-purple-50 text-purple-700 border-purple-200"
                                : m.level === "Pacheca Plus"
                                ? "bg-blue-50 text-blue-700 border-blue-200"
                                : "bg-gray-50 text-text-dark border-gray-200"
                            }`}>
                              {m.level}
                            </span>
                          </td>
                          <td className="p-4 text-right font-bold text-text-dark">{m.points_balance} pts</td>
                          <td className="p-4 text-right text-text-muted">{m.points_pending || 0} pts</td>
                          <td className="p-4 text-center">
                            {m.is_blocked ? (
                              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[9px] font-bold bg-red-50 text-error border border-red-200">
                                <Ban className="h-2.5 w-2.5 mr-0.5" /> Bloqueado
                              </span>
                            ) : (
                              <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[9px] font-bold bg-emerald-50 text-success border border-emerald-200">
                                <Check className="h-2.5 w-2.5 mr-0.5" /> Activo
                              </span>
                            )}
                          </td>
                          <td className="p-4 text-right">
                            <button
                              onClick={() => setSelectedMember(m)}
                              className="text-accent hover:underline font-bold"
                            >
                              Ver Ficha
                            </button>
                          </td>
                        </tr>
                      );
                    })
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Member Details Sidebar / Modal overlay */}
          {selectedMember && (
            <div className="fixed inset-0 bg-black/50 backdrop-blur-xs flex items-center justify-center z-50 p-4">
              <div className="bg-white rounded-xl shadow-xl max-w-2xl w-full p-6 space-y-5 max-h-[90vh] overflow-y-auto border border-border-brand">
                
                {/* Header detail */}
                <div className="flex justify-between items-start border-b border-border-brand pb-3">
                  <div>
                    <h3 className="font-display font-bold text-text-dark uppercase tracking-wider text-base">
                      Ficha de Miembro Pacheca
                    </h3>
                    <p className="text-[10px] text-text-muted mt-0.5">ID: {selectedMember.id}</p>
                  </div>
                  <button
                    onClick={() => setSelectedMember(null)}
                    className="text-text-muted hover:text-text-dark"
                  >
                    <X className="h-5 w-5" />
                  </button>
                </div>

                {/* Profile Grid */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
                  <div className="space-y-2 border border-border-brand p-3 rounded-lg bg-bg-light">
                    <p className="font-bold text-[10px] uppercase text-text-muted tracking-wider">Datos Personales</p>
                    {(() => {
                      const profile = mockDb.profiles.find(p => p.id === selectedMember.profile_id);
                      const cust = mockDb.customers.find(c => c.profile_id === selectedMember.profile_id);
                      return (
                        <div className="space-y-1 text-text-dark">
                          <p><strong>Nombre:</strong> {profile ? `${profile.first_name} ${profile.last_name}` : "N/A"}</p>
                          <p><strong>Email:</strong> {profile?.email || "N/A"}</p>
                          <p><strong>WhatsApp:</strong> {cust?.whatsapp || "N/A"}</p>
                          <p><strong>Cumpleaños:</strong> {selectedMember.birthday ? new Date(selectedMember.birthday).toLocaleDateString("es-AR") : "No registrado"}</p>
                          <p><strong>Registrada el:</strong> {new Date(selectedMember.registered_at).toLocaleDateString()}</p>
                        </div>
                      );
                    })()}
                  </div>

                  <div className="space-y-2 border border-border-brand p-3 rounded-lg bg-bg-light">
                    <p className="font-bold text-[10px] uppercase text-text-muted tracking-wider">Estado Club Pacheca</p>
                    <div className="space-y-1.5 text-text-dark">
                      <p><strong>Puntos Balance:</strong> <span className="font-bold text-accent">{selectedMember.points_balance} pts</span></p>
                      <p><strong>Puntos Pendientes:</strong> {selectedMember.points_pending || 0} pts</p>
                      <p><strong>Código de Referido:</strong> <span className="font-mono font-bold">{selectedMember.referral_code}</span></p>
                      
                      {/* Edit Nivel */}
                      <div className="flex items-center space-x-2 mt-1">
                        <strong>Nivel:</strong>
                        <select
                          value={selectedMember.level}
                          onChange={(e) => handleChangeLevel(selectedMember.id, e.target.value as any)}
                          className="text-xs p-1 border border-border-brand rounded focus:outline-none"
                        >
                          <option value="Pacheca">Pacheca</option>
                          <option value="Pacheca Plus">Pacheca Plus</option>
                          <option value="Pacheca VIP">Pacheca VIP</option>
                        </select>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Actions Panel */}
                <div className="flex flex-wrap gap-2 border-t border-b border-border-brand py-3">
                  <button
                    onClick={() => setShowAdjustPointsModal(true)}
                    className="px-3 py-1.5 text-[11px] bg-black text-white hover:bg-neutral-800 rounded font-bold uppercase tracking-wider shadow-2xs"
                  >
                    Ajustar Puntos
                  </button>
                  <button
                    onClick={() => handleToggleBlockMember(selectedMember.id)}
                    className={`px-3 py-1.5 text-[11px] rounded font-bold uppercase tracking-wider border ${
                      selectedMember.is_blocked
                        ? "border-emerald-300 text-success hover:bg-emerald-50"
                        : "border-red-300 text-error hover:bg-red-50"
                    }`}
                  >
                    {selectedMember.is_blocked ? "Desbloquear Cuenta" : "Bloquear Cuenta"}
                  </button>
                </div>

                {/* Member History Tables */}
                <div className="space-y-4">
                  <h4 className="font-bold text-xs uppercase tracking-wider text-text-dark">Historial de Movimientos</h4>
                  <div className="max-h-40 overflow-y-auto border border-border-brand rounded-lg text-[11px]">
                    <table className="w-full text-left border-collapse">
                      <thead>
                        <tr className="bg-bg-light border-b border-border-brand font-bold text-text-muted">
                          <th className="p-2">Fecha</th>
                          <th className="p-2">Acción</th>
                          <th className="p-2">Descripción</th>
                          <th className="p-2 text-right">Puntos</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-border-brand">
                        {transactions.filter(t => t.member_id === selectedMember.id).length === 0 ? (
                          <tr>
                            <td colSpan={4} className="p-4 text-center text-text-muted">
                              Sin transacciones registradas.
                            </td>
                          </tr>
                        ) : (
                          transactions
                            .filter(t => t.member_id === selectedMember.id)
                            .sort((a,b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
                            .map(t => (
                              <tr key={t.id} className="hover:bg-bg-light/40">
                                <td className="p-2 text-text-muted">{new Date(t.created_at).toLocaleDateString()}</td>
                                <td className="p-2 capitalize text-text-dark font-medium">{t.action_type.replace("_", " ")}</td>
                                <td className="p-2 text-text-muted">{t.description}</td>
                                <td className={`p-2 text-right font-bold ${t.amount > 0 ? "text-success" : "text-error"}`}>
                                  {t.amount > 0 ? "+" : ""}{t.amount}
                                </td>
                              </tr>
                            ))
                        )}
                      </tbody>
                    </table>
                  </div>
                </div>

                {/* Audit notes log */}
                <div className="space-y-2">
                  <h4 className="font-bold text-xs uppercase tracking-wider text-text-dark">Notas internas de Auditoría</h4>
                  <div className="bg-bg-light p-3 rounded-lg text-[10px] font-mono text-text-muted max-h-30 overflow-y-auto space-y-1">
                    {mockDb.audit_logs
                      .filter(l => l.entity_id === selectedMember.id)
                      .map(l => (
                        <div key={l.id} className="border-b border-border-brand/40 pb-1">
                          <span className="text-text-dark">[{new Date(l.created_at).toLocaleDateString()} {new Date(l.created_at).toLocaleTimeString()}]</span> - {l.user_email}: {l.reason}
                        </div>
                      ))}
                    {mockDb.audit_logs.filter(l => l.entity_id === selectedMember.id).length === 0 && (
                      <p>Sin registros de auditoría para este miembro.</p>
                    )}
                  </div>
                </div>

              </div>
            </div>
          )}

          {/* Adjust points modal overlay */}
          {showAdjustPointsModal && selectedMember && (
            <div className="fixed inset-0 bg-black/60 backdrop-blur-xs flex items-center justify-center z-[60] p-4">
              <div className="bg-white rounded-xl shadow-xl max-w-sm w-full p-6 space-y-4 border border-border-brand">
                <div className="flex justify-between items-center border-b border-border-brand pb-3">
                  <h4 className="font-display font-bold text-text-dark uppercase tracking-wider text-xs">
                    Ajustar Puntos Manualmente
                  </h4>
                  <button onClick={() => setShowAdjustPointsModal(false)} className="text-text-muted">
                    <X className="h-4 w-4" />
                  </button>
                </div>

                <form onSubmit={handleAdjustPointsSubmit} className="space-y-4 text-xs">
                  <div>
                    <label className="block text-[10px] uppercase font-bold text-text-muted mb-1">
                      Puntos a sumar o restar
                    </label>
                    <input
                      type="number"
                      value={adjustAmount}
                      onChange={(e) => setAdjustAmount(parseInt(e.target.value) || 0)}
                      className="w-full p-2 border border-border-brand rounded focus:outline-none focus:border-accent text-sm"
                      placeholder="Ej. 100 o -50"
                    />
                    <p className="text-[10px] text-text-muted mt-1">Usá números negativos para restar puntos de la cuenta.</p>
                  </div>

                  <div>
                    <label className="block text-[10px] uppercase font-bold text-text-muted mb-1">
                      Motivo del ajuste
                    </label>
                    <textarea
                      required
                      rows={3}
                      value={adjustReason}
                      onChange={(e) => setAdjustReason(e.target.value)}
                      className="w-full p-2 border border-border-brand rounded focus:outline-none focus:border-accent"
                      placeholder="Escribí el motivo detallado de esta modificación manual..."
                    />
                  </div>

                  <div className="flex space-x-2 pt-2">
                    <button
                      type="button"
                      onClick={() => setShowAdjustPointsModal(false)}
                      className="w-1/2 py-2 border border-border-brand rounded hover:bg-bg-light font-bold uppercase tracking-wider"
                    >
                      Cancelar
                    </button>
                    <button
                      type="submit"
                      disabled={adjustAmount === 0 || !adjustReason.trim()}
                      className="w-1/2 py-2 bg-black text-white hover:bg-neutral-800 disabled:bg-neutral-300 rounded font-bold uppercase tracking-wider shadow-2xs"
                    >
                      Guardar
                    </button>
                  </div>
                </form>
              </div>
            </div>
          )}

        </div>
      )}

      {/* TAB CONTENT: MODERACION */}
      {activeTab === "moderacion" && (
        <div className="space-y-6">
          
          {/* Moderation sub-navigation */}
          <div className="flex border-b border-border-brand gap-4 text-xs">
            <button
              onClick={() => setModSubTab("reseñas")}
              className={`pb-2 font-bold uppercase tracking-wider border-b-2 transition-all ${
                modSubTab === "reseñas" ? "border-accent text-accent" : "border-transparent text-text-muted"
              }`}
            >
              Reseñas Pendientes ({pendingReviewsCount})
            </button>
            <button
              onClick={() => setModSubTab("fotos")}
              className={`pb-2 font-bold uppercase tracking-wider border-b-2 transition-all ${
                modSubTab === "fotos" ? "border-accent text-accent" : "border-transparent text-text-muted"
              }`}
            >
              Fotos Pendientes ({pendingPhotosCount})
            </button>
            <button
              onClick={() => setModSubTab("fraude")}
              className={`pb-2 font-bold uppercase tracking-wider border-b-2 transition-all ${
                modSubTab === "fraude" ? "border-accent text-accent" : "border-transparent text-text-muted"
              }`}
            >
              Alertas de Fraude ({pendingAlertsCount})
            </button>
          </div>

          {/* Sub-tab Review List */}
          {modSubTab === "reseñas" && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {reviews.filter(r => r.status === "pending").length === 0 ? (
                <div className="col-span-2 text-center py-12 border border-dashed border-border-brand rounded-xl bg-white">
                  <Star className="h-10 w-10 text-text-muted mx-auto mb-2" />
                  <p className="text-xs text-text-muted">No hay reseñas pendientes de aprobación en este momento.</p>
                </div>
              ) : (
                reviews.filter(r => r.status === "pending").map(r => (
                  <div key={r.id} className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-3 text-xs">
                    <div className="flex justify-between items-start">
                      <div>
                        <p className="font-bold text-text-dark">{r.customer_name}</p>
                        <p className="text-[10px] text-text-muted">Producto: {r.product_name || "N/A"}</p>
                        {r.size_purchased && <p className="text-[9px] text-text-muted">Talle: {r.size_purchased} | Calce: {r.fit_opinion}</p>}
                      </div>
                      <div className="flex items-center space-x-0.5">
                        {[1,2,3,4,5].map(star => (
                          <Star key={star} className={`h-3 w-3 ${star <= r.rating ? "text-accent fill-accent" : "text-gray-200"}`} />
                        ))}
                      </div>
                    </div>
                    
                    <p className="text-text-muted italic border-l-2 border-border-brand pl-2 bg-bg-light/40 py-1">
                      &quot;{r.comment}&quot;
                    </p>

                    <div className="flex justify-end space-x-2 pt-2">
                      <button
                        onClick={() => handleRejectReview(r.id)}
                        className="px-2.5 py-1.5 text-[10px] border border-red-300 text-error hover:bg-red-50 rounded font-bold uppercase tracking-wider"
                      >
                        Rechazar
                      </button>
                      <button
                        onClick={() => handleApproveReview(r.id)}
                        className="px-2.5 py-1.5 text-[10px] bg-black text-white hover:bg-neutral-800 rounded font-bold uppercase tracking-wider flex items-center gap-1 shadow-2xs"
                      >
                        <Check className="h-3 w-3" /> Aprobar y Sumar {config?.points_per_review} Pts
                      </button>
                    </div>
                  </div>
                ))
              )}
            </div>
          )}

          {/* Sub-tab Photos List */}
          {modSubTab === "fotos" && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {photos.filter(p => p.status === "pending").length === 0 ? (
                <div className="col-span-2 text-center py-12 border border-dashed border-border-brand rounded-xl bg-white">
                  <Camera className="h-10 w-10 text-text-muted mx-auto mb-2" />
                  <p className="text-xs text-text-muted">No hay fotos pendientes de aprobación en este momento.</p>
                </div>
              ) : (
                photos.filter(p => p.status === "pending").map(p => {
                  const member = mockDb.club_members.find(m => m.id === p.member_id);
                  const profile = member ? mockDb.profiles.find(pr => pr.id === member.profile_id) : null;
                  const productName = mockDb.products.find(prod => prod.id === p.product_id)?.name_public || "Prenda";
                  return (
                    <div key={p.id} className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-3 text-xs flex flex-col sm:flex-row gap-4">
                      
                      {/* Photo preview */}
                      <div className="h-36 w-full sm:w-28 rounded-lg overflow-hidden border border-border-brand shrink-0">
                        <img src={p.image_url} alt="Look de clienta" className="h-full w-full object-cover" />
                      </div>

                      {/* Detail info */}
                      <div className="flex-1 flex flex-col justify-between">
                        <div className="space-y-1">
                          <p className="font-bold text-text-dark">Clienta: {profile ? `${profile.first_name} ${profile.last_name}` : "N/A"}</p>
                          <p className="text-[10px] text-text-muted">Prenda: {productName} (Talle: {p.size_used})</p>
                          {p.comment && <p className="italic text-text-muted mt-1">&quot;{p.comment}&quot;</p>}
                          <p className="text-[9px] text-accent font-semibold mt-1">Autorización de publicación: ACEPTADA ✅</p>
                        </div>

                        <div className="flex justify-end space-x-2 pt-3">
                          <button
                            onClick={() => handleRejectPhoto(p.id)}
                            className="px-2.5 py-1.5 text-[10px] border border-red-300 text-error hover:bg-red-50 rounded font-bold uppercase tracking-wider"
                          >
                            Rechazar
                          </button>
                          <button
                            onClick={() => handleApprovePhoto(p.id)}
                            className="px-2.5 py-1.5 text-[10px] bg-black text-white hover:bg-neutral-800 rounded font-bold uppercase tracking-wider flex items-center gap-1 shadow-2xs"
                          >
                            <Check className="h-3 w-3" /> Aprobar y Sumar {config?.points_per_photo} Pts
                          </button>
                        </div>
                      </div>

                    </div>
                  );
                })
              )}
            </div>
          )}

          {/* Sub-tab Alerts List */}
          {modSubTab === "fraude" && (
            <div className="space-y-4">
              {alerts.filter(a => a.status === "requiere_revision").length === 0 ? (
                <div className="text-center py-12 border border-dashed border-border-brand rounded-xl bg-white">
                  <ShieldAlert className="h-10 w-10 text-text-muted mx-auto mb-2" />
                  <p className="text-xs text-text-muted">No hay alertas sospechosas requiriendo revisión en este momento.</p>
                </div>
              ) : (
                alerts.filter(a => a.status === "requiere_revision").map(a => {
                  const referrerMember = mockDb.club_members.find(m => m.id === a.member_id);
                  const referrerProfile = referrerMember ? mockDb.profiles.find(p => p.id === referrerMember.profile_id) : null;
                  
                  return (
                    <div key={a.id} className="bg-white border border-red-200 p-4 rounded-xl shadow-2xs space-y-3 text-xs">
                      <div className="flex justify-between items-start">
                        <div className="flex items-center space-x-2 text-error">
                          <AlertTriangle className="h-4 w-4" />
                          <span className="font-bold uppercase tracking-wider text-[10px]">Alerta Antifraude</span>
                        </div>
                        <span className="text-[10px] text-text-muted">{new Date(a.created_at).toLocaleDateString()}</span>
                      </div>
                      
                      <div className="space-y-1.5">
                        <p className="font-bold text-text-dark">{a.description}</p>
                        {referrerProfile && (
                          <p className="text-[10px] text-text-muted">
                            Miembro Referidor: {referrerProfile.first_name} {referrerProfile.last_name} ({referrerProfile.email}) | Código: {referrerMember?.referral_code}
                          </p>
                        )}
                      </div>

                      <div className="flex justify-end space-x-2 pt-2 border-t border-border-brand/40">
                        <button
                          onClick={() => handleResolveAlert(a.id, "aprobado")}
                          className="px-3 py-1.5 text-[10px] border border-emerald-300 text-success hover:bg-emerald-50 rounded font-bold uppercase tracking-wider"
                        >
                          Aprobar Referido
                        </button>
                        <button
                          onClick={() => handleResolveAlert(a.id, "bloqueado")}
                          className="px-3 py-1.5 text-[10px] bg-red-600 text-white hover:bg-red-700 rounded font-bold uppercase tracking-wider shadow-2xs"
                        >
                          Bloquear Cuenta
                        </button>
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          )}

        </div>
      )}

      {/* TAB CONTENT: PREMIOS CATALOGO */}
      {activeTab === "premios" && (
        <div className="space-y-6">
          <div className="flex justify-between items-center">
            <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark">Catálogo de Canje Vigente</h3>
            <button
              onClick={handleOpenNewRewardModal}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-black text-white hover:bg-neutral-800 text-xs font-bold uppercase tracking-wider rounded-lg transition-colors shadow-2xs"
            >
              <Plus className="h-4 w-4" /> Nuevo Premio
            </button>
          </div>

          {/* Catalog Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {rewards.map(reward => (
              <div
                key={reward.id}
                className={`bg-white border p-5 rounded-xl shadow-2xs space-y-4 relative flex flex-col justify-between ${
                  reward.is_active ? "border-border-brand" : "border-dashed border-gray-300 opacity-60"
                }`}
              >
                <div className="space-y-2">
                  <div className="flex justify-between items-start">
                    <span className="inline-flex items-center px-2 py-0.5 rounded-full text-[9px] font-extrabold bg-accent/10 text-accent border border-accent/20">
                      {reward.points_required} Puntos
                    </span>
                    <span className={`text-[9px] font-bold uppercase ${reward.is_active ? "text-success" : "text-text-muted"}`}>
                      {reward.is_active ? "Activo" : "Inactivo"}
                    </span>
                  </div>
                  
                  <div>
                    <h4 className="font-bold text-sm text-text-dark">{reward.name}</h4>
                    <p className="text-xs text-text-muted mt-1 leading-tight">{reward.description}</p>
                  </div>

                  <div className="text-[10px] text-text-muted space-y-1 pt-1 border-t border-border-brand/40">
                    <p><strong>Beneficio:</strong> {reward.benefit_type === "percentage" ? `${reward.benefit_value}% Descuento` : reward.benefit_type === "fixed_amount" ? `$${reward.benefit_value} Descuento` : reward.benefit_type === "free_shipping" ? "Envío Gratis" : "Regalo Sorpresa"}</p>
                    <p><strong>Compra Mínima:</strong> ${reward.min_purchase_amount}</p>
                    <p><strong>Expiración:</strong> {reward.expires_days} días</p>
                    <p><strong>Stock disponible:</strong> {reward.stock} unidades</p>
                  </div>
                </div>

                <div className="flex justify-end space-x-2 pt-4 border-t border-border-brand/40">
                  <button
                    onClick={() => handleDeleteReward(reward.id)}
                    className="p-1.5 text-text-muted hover:text-error border border-transparent hover:border-red-200 hover:bg-red-50 rounded transition-colors"
                    title="Eliminar"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                  <button
                    onClick={() => handleOpenEditRewardModal(reward)}
                    className="p-1.5 text-text-muted hover:text-accent border border-transparent hover:border-accent/20 hover:bg-accent/5 rounded transition-colors"
                    title="Editar"
                  >
                    <Edit2 className="h-4 w-4" />
                  </button>
                </div>
              </div>
            ))}
          </div>

          {/* Reward Create/Edit Modal */}
          {showRewardModal && (
            <div className="fixed inset-0 bg-black/50 backdrop-blur-xs flex items-center justify-center z-50 p-4">
              <div className="bg-white rounded-xl shadow-xl max-w-md w-full p-6 space-y-4 border border-border-brand max-h-[90vh] overflow-y-auto">
                <div className="flex justify-between items-center border-b border-border-brand pb-3">
                  <h4 className="font-display font-bold text-text-dark uppercase tracking-wider text-xs">
                    {editingReward ? "Editar Recompensa" : "Nueva Recompensa"}
                  </h4>
                  <button onClick={() => setShowRewardModal(false)} className="text-text-muted">
                    <X className="h-5 w-5" />
                  </button>
                </div>

                <form onSubmit={handleRewardSubmit} className="space-y-3 text-xs">
                  <div>
                    <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Nombre del Premio</label>
                    <input
                      type="text"
                      required
                      value={rewardForm.name}
                      onChange={(e) => setRewardForm({ ...rewardForm, name: e.target.value })}
                      placeholder="Ej. 10% de descuento"
                      className="w-full p-2 border border-border-brand rounded focus:outline-none focus:border-accent"
                    />
                  </div>

                  <div>
                    <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Descripción</label>
                    <input
                      type="text"
                      required
                      value={rewardForm.description}
                      onChange={(e) => setRewardForm({ ...rewardForm, description: e.target.value })}
                      placeholder="Ej. Válido para toda la tienda en compras superiores a..."
                      className="w-full p-2 border border-border-brand rounded focus:outline-none focus:border-accent"
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Puntos requeridos</label>
                      <input
                        type="number"
                        required
                        value={rewardForm.points_required}
                        onChange={(e) => setRewardForm({ ...rewardForm, points_required: parseInt(e.target.value) || 0 })}
                        className="w-full p-2 border border-border-brand rounded focus:outline-none"
                      />
                    </div>
                    <div>
                      <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Stock</label>
                      <input
                        type="number"
                        required
                        value={rewardForm.stock}
                        onChange={(e) => setRewardForm({ ...rewardForm, stock: parseInt(e.target.value) || 0 })}
                        className="w-full p-2 border border-border-brand rounded focus:outline-none"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Tipo beneficio</label>
                      <select
                        value={rewardForm.benefit_type}
                        onChange={(e) => setRewardForm({ ...rewardForm, benefit_type: e.target.value as any })}
                        className="w-full p-2 border border-border-brand rounded focus:outline-none focus:border-accent"
                      >
                        <option value="percentage">Porcentaje (%)</option>
                        <option value="fixed_amount">Monto Fijo ($)</option>
                        <option value="free_shipping">Envío Gratis</option>
                        <option value="free_gift">Regalo Sorpresa</option>
                      </select>
                    </div>
                    <div>
                      <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Valor beneficio</label>
                      <input
                        type="number"
                        required
                        value={rewardForm.benefit_value}
                        onChange={(e) => setRewardForm({ ...rewardForm, benefit_value: parseFloat(e.target.value) || 0 })}
                        className="w-full p-2 border border-border-brand rounded focus:outline-none"
                        disabled={rewardForm.benefit_type === "free_shipping" || rewardForm.benefit_type === "free_gift"}
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-3">
                    <div>
                      <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Compra Mínima ($)</label>
                      <input
                        type="number"
                        required
                        value={rewardForm.min_purchase_amount}
                        onChange={(e) => setRewardForm({ ...rewardForm, min_purchase_amount: parseFloat(e.target.value) || 0 })}
                        className="w-full p-2 border border-border-brand rounded focus:outline-none"
                      />
                    </div>
                    <div>
                      <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Días de validez</label>
                      <input
                        type="number"
                        required
                        value={rewardForm.expires_days}
                        onChange={(e) => setRewardForm({ ...rewardForm, expires_days: parseInt(e.target.value) || 0 })}
                        className="w-full p-2 border border-border-brand rounded focus:outline-none"
                      />
                    </div>
                  </div>

                  <div className="flex items-center space-x-2 pt-2">
                    <input
                      type="checkbox"
                      id="rewardActive"
                      checked={rewardForm.is_active}
                      onChange={(e) => setRewardForm({ ...rewardForm, is_active: e.target.checked })}
                      className="rounded text-accent focus:ring-accent"
                    />
                    <label htmlFor="rewardActive" className="font-bold text-text-dark">Activar inmediatamente en el catálogo</label>
                  </div>

                  <div className="flex space-x-2 pt-4 border-t border-border-brand/40">
                    <button
                      type="button"
                      onClick={() => setShowRewardModal(false)}
                      className="w-1/2 py-2.5 border border-border-brand rounded font-bold uppercase tracking-wider"
                    >
                      Cancelar
                    </button>
                    <button
                      type="submit"
                      className="w-1/2 py-2.5 bg-black text-white hover:bg-neutral-800 rounded font-bold uppercase tracking-wider shadow-2xs"
                    >
                      Guardar Premio
                    </button>
                  </div>
                </form>
              </div>
            </div>
          )}

        </div>
      )}

      {/* TAB CONTENT: CONFIG */}
      {activeTab === "config" && config && (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          
          {/* Rules Configuration */}
          <div className="bg-white border border-border-brand p-5 rounded-xl shadow-2xs space-y-4">
            <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center border-b border-border-brand pb-2">
              <Settings className="h-4 w-4 mr-2 text-accent" />
              Equivalencias de Puntos
            </h3>
            
            <div className="space-y-4 text-xs">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Puntos de Bienvenida</label>
                  <input
                    type="number"
                    value={config.points_welcome}
                    onChange={(e) => handleConfigUpdate({ points_welcome: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Monto por 1 punto ($)</label>
                  <input
                    type="number"
                    value={config.money_to_points_ratio}
                    onChange={(e) => handleConfigUpdate({ money_to_points_ratio: parseInt(e.target.value) || 1 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Puntos por Reseña</label>
                  <input
                    type="number"
                    value={config.points_per_review}
                    onChange={(e) => handleConfigUpdate({ points_per_review: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Puntos por subir Foto</label>
                  <input
                    type="number"
                    value={config.points_per_photo}
                    onChange={(e) => handleConfigUpdate({ points_per_photo: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Puntos por Referido</label>
                  <input
                    type="number"
                    value={config.points_per_referral}
                    onChange={(e) => handleConfigUpdate({ points_per_referral: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Vencimiento Puntos (días)</label>
                  <input
                    type="number"
                    value={config.points_expiry_days}
                    onChange={(e) => handleConfigUpdate({ points_expiry_days: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
              </div>
            </div>
          </div>

          {/* Referral Rules Configuration */}
          <div className="bg-white border border-border-brand p-5 rounded-xl shadow-2xs space-y-4">
            <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center border-b border-border-brand pb-2">
              <Users className="h-4 w-4 mr-2 text-success" />
              Límites y Reglas de Referidos
            </h3>

            <div className="space-y-4 text-xs">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Dcto. Amiga Invitada (%)</label>
                  <input
                    type="number"
                    value={config.referral_discount_friend}
                    onChange={(e) => handleConfigUpdate({ referral_discount_friend: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Dcto. Quien Recomienda (%)</label>
                  <input
                    type="number"
                    value={config.referral_discount_referrer}
                    onChange={(e) => handleConfigUpdate({ referral_discount_referrer: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Monto Mínimo Compra ($)</label>
                  <input
                    type="number"
                    value={config.min_purchase_for_referral_benefit}
                    onChange={(e) => handleConfigUpdate({ min_purchase_for_referral_benefit: parseFloat(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
                <div>
                  <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Vencimiento Cupón (días)</label>
                  <input
                    type="number"
                    value={config.referral_coupon_expiry_days}
                    onChange={(e) => handleConfigUpdate({ referral_coupon_expiry_days: parseInt(e.target.value) || 0 })}
                    className="w-full p-2 border border-border-brand rounded focus:outline-none"
                  />
                </div>
              </div>

              <div>
                <label className="block text-[9px] uppercase font-bold text-text-muted mb-1">Mensaje de WhatsApp predeterminado para compartir</label>
                <div className="w-full p-2.5 bg-bg-light border border-border-brand rounded-lg text-text-muted select-none text-[11px] leading-relaxed font-sans">
                  ¡Hola! Te invito a conocer Pacheca 💕 Usando mi enlace recibís un 5% de descuento en tu primera compra: {"{ENLACE_PERSONAL}"}
                </div>
              </div>
            </div>
          </div>

        </div>
      )}

      {/* TAB CONTENT: ANALITICAS */}
      {activeTab === "analiticas" && (
        <div className="space-y-6">
          
          {/* Analytical Grid */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* ROI Simulator Card */}
            <div className="bg-white border border-border-brand p-5 rounded-xl shadow-2xs space-y-4 col-span-1 md:col-span-2">
              <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center border-b border-border-brand pb-2">
                <BarChart2 className="h-4 w-4 mr-2 text-success" />
                Retorno de la Inversión (ROI) - Club Pacheca
              </h3>

              <div className="grid grid-cols-2 gap-4 text-xs">
                <div className="bg-bg-light p-3 rounded-lg">
                  <p className="text-[10px] text-text-muted font-bold uppercase">Ingresos por referidos</p>
                  <p className="text-lg font-bold text-success mt-1">
                    {new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" }).format(referralOrdersRevenue)}
                  </p>
                </div>
                
                <div className="bg-bg-light p-3 rounded-lg">
                  <p className="text-[10px] text-text-muted font-bold uppercase">Costo estimado descuentos</p>
                  <p className="text-lg font-bold text-error mt-1">
                    {new Intl.NumberFormat("es-AR", { style: "currency", currency: "ARS" }).format(totalVoucherDiscountCosts)}
                  </p>
                </div>
              </div>

              <div className="p-3 border border-border-brand rounded-lg bg-emerald-50/50 flex justify-between items-center text-xs">
                <div>
                  <p className="font-bold text-text-dark">Retorno ROI Estimado</p>
                  <p className="text-[10px] text-text-muted">Ingresos generados vs costo de descuentos aplicados</p>
                </div>
                <div className="text-right">
                  <p className="text-base font-extrabold text-success">
                    {totalVoucherDiscountCosts > 0 
                      ? `+${((referralOrdersRevenue - totalVoucherDiscountCosts) / totalVoucherDiscountCosts * 100).toFixed(0)}%`
                      : "+100%"}
                  </p>
                </div>
              </div>
            </div>

            {/* Recompensas más canjeadas */}
            <div className="bg-white border border-border-brand p-5 rounded-xl shadow-2xs space-y-4">
              <h3 className="font-bold text-xs uppercase tracking-wider text-text-dark flex items-center border-b border-border-brand pb-2">
                <Gift className="h-4 w-4 mr-2 text-accent" />
                Premios Más Canjeados
              </h3>

              <div className="space-y-3 text-xs">
                {rewards.slice(0, 3).map((r, i) => {
                  const redeemCount = transactions.filter(t => t.amount < 0 && t.description.includes(r.name)).length;
                  return (
                    <div key={r.id} className="flex justify-between items-center">
                      <div className="flex items-center space-x-2">
                        <span className="font-bold text-text-muted">{i+1}.</span>
                        <span className="text-text-dark font-medium">{r.name}</span>
                      </div>
                      <span className="font-bold text-text-muted">{redeemCount} canjes</span>
                    </div>
                  );
                })}
              </div>
            </div>

          </div>

          {/* Gamification / Engagement statistics */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 text-xs">
            
            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-2">
              <h4 className="font-bold uppercase tracking-wider text-text-muted text-[10px]">Frecuencia de Compra</h4>
              <p className="text-lg font-bold text-text-dark">Cada 45 días promedio</p>
              <p className="text-[10px] text-text-muted">Miembros del club compran 1.8x más seguido que clientas externas.</p>
            </div>

            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-2">
              <h4 className="font-bold uppercase tracking-wider text-text-muted text-[10px]">Clientas Recurrentes</h4>
              <p className="text-lg font-bold text-text-dark">{recurringMembersCount} miembros</p>
              <p className="text-[10px] text-text-muted">Miembros con 2 o más reservas finalizadas en el local.</p>
            </div>

            <div className="bg-white border border-border-brand p-4 rounded-xl shadow-2xs space-y-2">
              <h4 className="font-bold uppercase tracking-wider text-text-muted text-[10px]">Contenido Generado (UGC)</h4>
              <p className="text-lg font-bold text-text-dark">
                {reviews.length} opiniones & {photos.length} looks
              </p>
              <p className="text-[10px] text-text-muted">Total de contenido subido y moderado para marketing de Pacheca.</p>
            </div>

          </div>

        </div>
      )}

    </div>
  );
}
